name: ReddCraft
main: com.reddcoin.bukkit.reddcraft.ReddCraftPlugin
version: ${version}
commands:
    account:
        description: Displays your ReddCoin-address and its balance.
        usage: "Usage: '/account' to display your username and Reddcoin-address"
        permission: reddcraft.account
    balance:
        description: Displays your current ReddCoin-balance.
        usage: "Usage: '/balance' to display your current Reddcoin-balance"
        permission: reddcraft.balance
    donate:
        description: Donate Reddcoins to this server.
        usage: "Usage: '/donate AMOUNT' to donate a certain of Reddcoins to this server"
        permission: reddcraft.donate
    pay:
        description: Pay a player an amount of Reddcoins.
        usage: "Usage: '/pay PLAYERNAME AMOUNT' to pay a certain of Reddcoins to a specific player"
        permission: reddcraft.pay
    tip:
        description: Tip a player an amount of Reddcoins.
        usage: "Usage: '/tip PLAYERNAME AMOUNT' to tip a certain of Reddcoins to a specific player"
        permission: reddcraft.tip
    withdraw:
        description: (0.5% FEE) Withdraw Reddcoins from your ReddCraft-account.
        usage: "Usage: '/withdraw ADDRESS AMOUNT' to withdraw Reddcoins to a specific address"
        permission: reddcraft.withdraw
permissions:
    reddcraft.*:
        description: Gives access to all ReddCraft commands
        children:
            reddcraft.account: true
            reddcraft.balance: true
            reddcraft.donate: true
            reddcraft.pay: true
            reddcraft.tip: true
            reddcraft.withdraw: true
    reddcraft.account:
        description: Allows usage of /account
        default: true
    reddcraft.balance:
        description: Allows usage of /balance
        default: true
    reddcraft.donate:
        description: Allows usage of /donate
        default: true
    reddcraft.pay:
        description: Allows usage of /pay
        default: true
    reddcraft.tip:
        description: Allows usage of /tip
        default: true
    reddcraft.withdraw:
        description: Allows usage of /withdraw
        default: true